repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: pretty-format-json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.4
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_trivy
        args:
          - --args=--tf-exclude-downloaded-modules
          - --args=--skip-dirs="**/.terraform"

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.440
    hooks:
      - id: checkov
