name: autoupdate

on:
  push:
    branches:
      - main

jobs:
  call-autoupdate:
    permissions:
      pull-requests: write
      contents: write
    uses: hche608/github-workflows/.github/workflows/pr-update.yml@main
    with:
      owner: ${{ github.repository_owner }}
      repo: ${{ github.event.repository.name }}
    secrets:
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
